repos:
  - repo: local
    hooks:
      - id: isort
        name: Isort
        entry: isort
        args: ['--profile=black']
        language: python
        types: [python]

      - id: black
        name: Black
        entry: black
        args: [
          '--exclude', '\\.venv|\\.git|\\.flake8|\\.pre-commit-config\\.yaml|pyproject\\.toml|mypy\\.ini|\\.gitignore|README\\.md|poetry\\.lock|requirements\\.txt|.*\\.ipynb'
        ]
        language: python
        types: [python]

      - id: flake8
        name: Flake8
        entry: flake8
        args: ['.', '--config', '.flake8']
        language: python
        types: [python]

      - id: mypy
        name: Mypy
        entry: mypy
        args: ['--ignore-missing-imports', '--explicit-package-bases', '--config-file', 'mypy.ini', 'src/']
        language: python
        types: [python]
        pass_filenames: false
